version: "3.8"

services:
  postgres:
    image: postgres:15.4
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: podrezova
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d podrezova"]
      interval: 10s
      timeout: 5s
      retries: 5

  python_app:
    build:
      context: ./python_app
    container_name: python_app_container
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    command: ["python", "main.py"]

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
